[workspace]
authors = ["Sasaki_ubuntu <0704waffle@gmail.com>"]
channels = ["pytorch", "nvidia", "conda-forge", "main", "r", "msys2"]
name = "opticalflow"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
_libgcc_mutex = { version = "==0.1", build = "main" }
_openmp_mutex = { version = "==5.1", build = "1_gnu" }
asttokens = { version = "==2.4.1", build = "pyhd8ed1ab_0" }
backcall = { version = "==0.2.0", build = "pyh9f0ad1d_0" }
blas = { version = "==1.0", build = "mkl" }
bzip2 = { version = "==1.0.8", build = "h5eee18b_5" }
ca-certificates = { version = "==2024.2.2", build = "hbcca054_0" }
certifi = { version = "==2024.2.2", build = "pyhd8ed1ab_0" }
charset-normalizer = { version = "==2.0.4", build = "pyhd3eb1b0_0" }
comm = { version = "==0.2.2", build = "pyhd8ed1ab_0" }
cuda-cudart = { version = "==12.1.105", build = "0" }
cuda-cupti = { version = "==12.1.105", build = "0" }
cuda-libraries = { version = "==12.1.0", build = "0" }
cuda-nvrtc = { version = "==12.1.105", build = "0" }
cuda-nvtx = { version = "==12.1.105", build = "0" }
cuda-opencl = { version = "==12.4.99", build = "0" }
cuda-runtime = { version = "==12.1.0", build = "0" }
debugpy = { version = "==1.6.7", build = "py39h6a678d5_0" }
decorator = { version = "==5.1.1", build = "pyhd8ed1ab_0" }
entrypoints = { version = "==0.4", build = "pyhd8ed1ab_0" }
executing = { version = "==2.0.1", build = "pyhd8ed1ab_0" }
ffmpeg = { version = "==4.3", build = "hf484d3e_0" }
filelock = { version = "==3.13.1", build = "py39h06a4308_0" }
freetype = { version = "==2.12.1", build = "h4a9f257_0" }
gmp = { version = "==6.2.1", build = "h295c915_3" }
gmpy2 = { version = "==2.1.2", build = "py39heeb90bb_0" }
gnutls = { version = "==3.6.15", build = "he1e5248_0" }
idna = { version = "==3.4", build = "py39h06a4308_0" }
intel-openmp = { version = "==2021.4.0", build = "h06a4308_3561" }
ipykernel = { version = "==6.29.3", build = "pyhd33586a_0" }
ipython = { version = "==8.12.0", build = "pyh41d4057_0" }
jedi = { version = "==0.19.1", build = "pyhd8ed1ab_0" }
jinja2 = { version = "==3.1.3", build = "py39h06a4308_0" }
jpeg = { version = "==9e", build = "h5eee18b_1" }
jupyter_client = { version = "==7.3.4", build = "pyhd8ed1ab_0" }
jupyter_core = { version = "==5.7.2", build = "py39hf3d152e_0" }
lame = { version = "==3.100", build = "h7b6447c_0" }
lcms2 = { version = "==2.12", build = "h3be6417_0" }
ld_impl_linux-64 = { version = "==2.38", build = "h1181459_1" }
lerc = { version = "==3.0", build = "h295c915_0" }
libcublas = { version = "==12.1.0.26", build = "0" }
libcufft = { version = "==11.0.2.4", build = "0" }
libcufile = { version = "==1.9.0.20", build = "0" }
libcurand = { version = "==10.3.5.119", build = "0" }
libcusolver = { version = "==11.4.4.55", build = "0" }
libcusparse = { version = "==12.0.2.55", build = "0" }
libdeflate = { version = "==1.17", build = "h5eee18b_1" }
libffi = { version = "==3.3", build = "he6710b0_2" }
libgcc-ng = { version = "==11.2.0", build = "h1234567_1" }
libgomp = { version = "==11.2.0", build = "h1234567_1" }
libiconv = { version = "==1.16", build = "h7f8727e_2" }
libidn2 = { version = "==2.3.4", build = "h5eee18b_0" }
libjpeg-turbo = { version = "==2.0.0", build = "h9bf148f_0" }
libnpp = { version = "==12.0.2.50", build = "0" }
libnvjitlink = { version = "==12.1.105", build = "0" }
libnvjpeg = { version = "==12.1.1.14", build = "0" }
libpng = { version = "==1.6.39", build = "h5eee18b_0" }
libsodium = { version = "==1.0.18", build = "h36c2ea0_1" }
libstdcxx-ng = { version = "==11.2.0", build = "h1234567_1" }
libtasn1 = { version = "==4.19.0", build = "h5eee18b_0" }
libtiff = { version = "==4.5.1", build = "h6a678d5_0" }
libunistring = { version = "==0.9.10", build = "h27cfd23_0" }
libwebp-base = { version = "==1.3.2", build = "h5eee18b_0" }
llvm-openmp = { version = "==14.0.6", build = "h9e868ea_0" }
lz4-c = { version = "==1.9.4", build = "h6a678d5_0" }
markupsafe = { version = "==2.1.3", build = "py39h5eee18b_0" }
matplotlib-inline = { version = "==0.1.6", build = "pyhd8ed1ab_0" }
mkl = { version = "==2021.4.0", build = "h06a4308_640" }
mkl-service = { version = "==2.4.0", build = "py39h7f8727e_0" }
mkl_fft = { version = "==1.3.1", build = "py39hd3c417c_0" }
mkl_random = { version = "==1.2.2", build = "py39h51133e4_0" }
mpc = { version = "==1.1.0", build = "h10f8cd9_1" }
mpfr = { version = "==4.0.2", build = "hb69a4c5_1" }
mpmath = { version = "==1.3.0", build = "py39h06a4308_0" }
ncurses = { version = "==6.4", build = "h6a678d5_0" }
nest-asyncio = { version = "==1.6.0", build = "pyhd8ed1ab_0" }
nettle = { version = "==3.7.3", build = "hbbd107a_1" }
networkx = { version = "==3.1", build = "py39h06a4308_0" }
numpy = { version = "==1.24.3", build = "py39h14f4228_0" }
numpy-base = { version = "==1.24.3", build = "py39h31eccc5_0" }
openh264 = { version = "==2.1.1", build = "h4ff587b_0" }
openjpeg = { version = "==2.4.0", build = "h3ad879b_0" }
openssl = { version = "==1.1.1l", build = "h7f98852_0" }
packaging = { version = "==24.0", build = "pyhd8ed1ab_0" }
parso = { version = "==0.8.3", build = "pyhd8ed1ab_0" }
pexpect = { version = "==4.9.0", build = "pyhd8ed1ab_0" }
pickleshare = { version = "==0.7.5", build = "py_1003" }
pillow = { version = "==10.2.0", build = "py39h5eee18b_0" }
pip = { version = "==23.3.1", build = "py39h06a4308_0" }
platformdirs = { version = "==4.2.0", build = "pyhd8ed1ab_0" }
prompt-toolkit = { version = "==3.0.42", build = "pyha770c72_0" }
prompt_toolkit = { version = "==3.0.42", build = "hd8ed1ab_0" }
psutil = { version = "==5.9.0", build = "py39h5eee18b_0" }
ptyprocess = { version = "==0.7.0", build = "pyhd3deb0d_0" }
pure_eval = { version = "==0.2.2", build = "pyhd8ed1ab_0" }
pygments = { version = "==2.17.2", build = "pyhd8ed1ab_0" }
python = { version = "==3.9.0", build = "hdb3f193_2" }
python_abi = { version = "==3.9", build = "2_cp39" }
pytorch = { version = "==2.2.1", build = "py3.9_cuda12.1_cudnn8.9.2_0" }
pytorch-cuda = { version = "==12.1", build = "ha16c6d3_5" }
pytorch-mutex = { version = "==1.0", build = "cuda" }
pyyaml = { version = "==6.0.1", build = "py39h5eee18b_0" }
pyzmq = { version = "==25.1.2", build = "py39h6a678d5_0" }
readline = { version = "==8.2", build = "h5eee18b_0" }
requests = { version = "==2.31.0", build = "py39h06a4308_1" }
setuptools = { version = "==68.2.2", build = "py39h06a4308_0" }
six = { version = "==1.16.0", build = "pyhd3eb1b0_1" }
sqlite = { version = "==3.41.2", build = "h5eee18b_0" }
stack_data = { version = "==0.6.2", build = "pyhd8ed1ab_0" }
sympy = { version = "==1.12", build = "py39h06a4308_0" }
tk = { version = "==8.6.12", build = "h1ccaba5_0" }
torchaudio = { version = "==2.2.1", build = "py39_cu121" }
torchtriton = { version = "==2.2.0", build = "py39" }
torchvision = { version = "==0.17.1", build = "py39_cu121" }
tornado = { version = "==6.1", build = "py39hb9d737c_3" }
traitlets = { version = "==5.14.2", build = "pyhd8ed1ab_0" }
typing_extensions = { version = "==4.9.0", build = "py39h06a4308_1" }
urllib3 = { version = "==2.1.0", build = "py39h06a4308_0" }
wcwidth = { version = "==0.2.13", build = "pyhd8ed1ab_0" }
wheel = { version = "==0.41.2", build = "py39h06a4308_0" }
xz = { version = "==5.4.6", build = "h5eee18b_0" }
yaml = { version = "==0.2.5", build = "h7b6447c_0" }
zeromq = { version = "==4.3.5", build = "h6a678d5_0" }
zlib = { version = "==1.2.13", build = "h5eee18b_0" }
zstd = { version = "==1.5.5", build = "hc292b87_0" }

[pypi-dependencies]
contourpy = "==1.2.0"
cupy-cuda12x = "==13.0.0"
cycler = "==0.12.1"
fastrlock = "==0.8.2"
fonttools = "==4.49.0"
fsspec = "==2024.2.0"
h5py = "==3.10.0"
huggingface-hub = "==0.21.4"
imageio = "==2.34.0"
importlib-resources = "==6.1.3"
kiwisolver = "==1.4.5"
lazy-loader = "==0.3"
mat73 = "==0.62"
matplotlib = "==3.8.3"
opencv-python = "==4.9.0.80"
pandas = "==2.2.1"
pyparsing = "==3.1.2"
python-dateutil = "==2.9.0.post0"
pytz = "==2024.1"
safetensors = "==0.4.2"
scikit-image = "==0.22.0"
scipy = "==1.12.0"
seaborn = "==0.13.2"
tabulate = "==0.9.0"
tifffile = "==2024.2.12"
timm = "==0.9.16"
torchsummary = "==1.5.1"
tqdm = "==4.66.2"
tzdata = "==2024.1"
zipp = "==3.17.0"
